repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        name: flake8 under python2
        language_version: python2
        exclude: ^doc/source/sphinxext/
    -   id: flake8
        name: flake8 under python3
        language_version: python3
        exclude: ^doc/source/sphinxext/

# Not ready yet
# -   repo: https://github.com/mgedmin/check-manifest
#     rev: "0.42"  # 0.43 needs recent git (--recurse-submodules option of
#                  # git ls-files)
#     hooks:
#     -   id: check-manifest
