version: ~> 1.0
# As of 2021-07-16, using the arm64 architecture is a way to use the Partner
# Queue, which is completely free of charge (whereas the default amd64
# queue consumes paid credits, or free "OSS credits" that we have to
# request from Travis Support). See this page for details:
# https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
arch:
  - arm64
os: linux
language: python
dist: bionic

jobs:
  include:
    # Remember to update the [travis] section of tox.ini.
    - python: 3.9
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5
    - python: 2.7
    # We may choose to deactivate the macOS builds at some point
    # because they are very expensive (50 credits per minute) and we do not
    # have a renewable credit allowance (credits must be requested repatedly
    # from support@travis-ci.com).
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: generic     # 'language: python' is an error on Travis CI macOS
  allow_failures:

install:
  - pip install tox-travis
  - |
    set -e # fail the script if any command fails
    if [[  "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PYTHON_VERSION" == "3.8" ]]; then
      pip install -U sphinx
      git clone https://github.com/brainvisa/brainvisa-cmake.git ../brainvisa-cmake
      PATH="$PWD/bin:$PATH" PYTHONPATH="$PWD/python:$PWD/../brainvisa-cmake/python:$PYTHONPATH" sphinx-build -b html doc/source "$PWD/doc/build_html"
      touch doc/build_html/.nojekyll
    fi
  - if [[ -n "$GITHUB_TOKEN" ]]; then export PUSH_DOC_TO_GH_PAGES=yes; fi

script: tox

deploy:
  provider: pages
  strategy: git
  edge: true # opt in to dpl v2 as recommended on https://docs.travis-ci.com/user/deployment/pages/
  cleanup: false
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: doc/build_html
  on:
    branch: master
    condition: $PUSH_DOC_TO_GH_PAGES == yes && $TRAVIS_OS_NAME == linux && $TRAVIS_PYTHON_VERSION == 3.8
